### ISSUE TITLE
Missing Bus Device requirement in setup.py

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_MS8607#1]
https://forums.adafruit.com/viewtopic.php?f=60&t=169030

We need to add Bus Device as a requirement so it is installed by pip as a dependency.

**Comment by ladyada** [comment]
@dherrada wanna try submitting a PR?

**Comment by evaherrada** [comment]
@ladyada Sure. I'd love to give it a go

**Comment by evaherrada** [comment]
Fixed in #2
